trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: AKS
  displayName: To AKS Stage
  jobs:
  - job: AKSjob
    displayName: to AKS Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      inputs:
        script: |
              echo "$(Pipeline.Workspace)"
              tree $(Pipeline.Workspace)
    - task: CmdLine@2
      inputs:
        script: |
          echo Write your commands here
          
          cat $(Pipeline.Workspace)/s/TodoApi/manifests/dep.yaml
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'kube-local-cluster-2'
        namespace: 'default'
        command: 'config view'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'kube-local-cluster-2'
        namespace: 'default'
        command: 'cluster-info'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'kube-local-cluster-2'
        namespace: 'default'
        command: 'version'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
    - task: KubernetesManifest@1
      displayName: Deploy
      inputs:
        kubernetesServiceConnection: kube-local-cluster-2
        namespace: default
        manifests: |
           $(Pipeline.Workspace)/s/TodoApi/manifests/dep.yaml
           $(Pipeline.Workspace)/s/TodoApi/manifests/services.yaml
        containers: wasishah102/api-mvc-in-mem