version: '3.8'

services:
  todoapi:
    image: mcr.microsoft.com/dotnet/aspnet:5.0
    container_name: todoapi
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    container_name: tododb
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql